name: Format Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.3'
      - name: Install JuliaFormatter
        run: julia -e 'import Pkg; Pkg.add("JuliaFormatter")'
      - name: Check Formatting
        run: julia -e 'using JuliaFormatter; format(".")'