name: Tests

on:
  push:
    branches:
      - main
      - dev-initial
  pull_request:
    branches:
      - main
      - dev-initial

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.3'
      - name: Install JuliaFormatter
        run: julia -e 'import Pkg; Pkg.add("JuliaFormatter")'
      - name: Check Formatting
        run: julia -e 'using JuliaFormatter; format(".")'

  test:
    runs-on: ubuntu-latest
    needs: format  # Assure que l'étape format s'est bien exécutée avant de lancer les tests
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.3'
      - name: Install Dependencies
        run: julia -e 'import Pkg; Pkg.activate("."); Pkg.instantiate()'
      - name: Run Tests
        run: julia -e 'Pkg.activate("."); Pkg.test()'
