name: Tests

on:
  push:
    branches:
      - main
      - dev-initial
      
  pull_request:
    branches:
      - main
      - dev-initial

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.3'
      - name: Install Dependencies
        run: julia -e 'import Pkg; Pkg.instantiate()'
      - name: Run CPU Tests
        run: julia -e 'import Pkg; Pkg.test()'

  gpu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.3'
      - name: Install CUDA.jl
        run: julia -e 'import Pkg; Pkg.add("CUDA")'
      - name: Run GPU Tests
        run: julia -e 'import Pkg; Pkg.test("test_gpu.jl")'
